# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-24 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('micasa', '0002_auto_20190324_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'Location'},
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(choices=[('Nairobi', 'Nairobi'), ('Kiambu', 'Kiambu'), ('Eastlands', 'Eastlands'), ('Machakos', 'Machakos'), ('Nakuru', 'Nakuru'), ('Thika', 'Thika')], default=django.utils.timezone.now, max_length=65),
            preserve_default=False,
        ),
    ]
