# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-24 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micasa', '0003_auto_20190324_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
    ]
